### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by doortts** [electron/devtron#109]
Symptom
--
When I try to use devtron v1.4 (latest) with electron 2.0 and click `Load Graph`, I met errors.

Tested
---
Also, I tested it with official page's quick start app.

Screen shot
---
![image](https://user-images.githubusercontent.com/520523/39741538-4ca61c34-52d5-11e8-8a39-13289a22dd9b.png)

![image](https://user-images.githubusercontent.com/520523/39741619-9b525e1a-52d5-11e8-98bf-cd8b447e461b.png)

![image](https://user-images.githubusercontent.com/520523/39742279-e031e3d2-52d7-11e8-9bb6-8988f0376aef.png)

Find condition
---
It works fine with devtron v1.4 and electron v1.8.x

**Comment by javan** [comment]
Seeing the same issue here on macOS 10.13.4
```sh
[91025:0508/094741.152446:ERROR:CONSOLE(1609)] "Loading render modules failed", source: chrome-extension://devtron/out/index.js (1609)
[91025:0508/094741.152538:ERROR:CONSOLE(1610)] "RangeError: Maximum call stack size exceeded
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)", source: chrome-extension://devtron/out/index.js (1610)
[91025:0508/094746.041946:ERROR:CONSOLE(1621)] "Loading main modules failed", source: chrome-extension://devtron/out/index.js (1621)
[91025:0508/094746.041992:ERROR:CONSOLE(1622)] "RangeError: Maximum call stack size exceeded
    at JSON.parse (<anonymous>)
    at EventEmitter.ipcRenderer.sendSync (/Users/javan/Work/basecamp/bc3-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/ipc-renderer.js:14:15)
    at Object.descriptor.get [as children] (/Users/javan/Work/basecamp/bc3-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:131:34)
    at walkModule (<anonymous>:21:26)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:21:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:21:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:21:35)", source: chrome-extension://devtron/out/index.js (1622)
```

```js
❯ process.versions
{
  "http_parser": "2.7.0",
  "node": "8.9.3",
  "v8": "6.1.534.41",
  "uv": "1.15.0",
  "zlib": "1.2.11",
  "ares": "1.10.1-DEV",
  "modules": "57",
  "nghttp2": "1.25.0",
  "openssl": "1.0.2n",
  "electron": "2.0.0",
  "chrome": "61.0.3163.100"
}
```

</details>

**Comment by lfallo1** [comment]
Same here (Electron v2.0.0, Devtron v1.4)... currently will need to revert to v1.8.6, to use Devtron.

**Comment by manny89** [comment]
Hit the same issue. I had to revert back to Electron v1.8.6 to use Devtron.

**Comment by doortts** [comment]
Dear @kevinsawicki 
sorry to bother you, but could I know there is any plan to resolve this problem?

**Comment by faridvatani** [comment]
I do have the same problem, I use Electron(3.0.2) & Devtron(1.4.0)
Has anyone got a solution to use higher electron versions?

**Comment by crashbdx** [comment]
Same here Electron 3.0.5 & Devtron 1.4.0, 

`[19416:1019/213823.143:ERROR:CONSOLE(1609)] "Loading render modules failed", source: chrome-extension://devtron/out/index.js (1609)
[19416:1019/213823.143:ERROR:CONSOLE(1610)] "RangeError: Maximum call stack size exceeded
    at walkModule (<anonymous>:12:24)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)", source: chrome-extension://devtron/out/index.js (1610)
[19416:1019/213832.657:ERROR:CONSOLE(1621)] "Loading main modules failed", source: chrome-extension://devtron/out/index.js (1621)`

any update ?

**Comment by shaheemMPM** [comment]
I've got the same
![screenshot 2018-10-20 at 7 30 16 pm](https://user-images.githubusercontent.com/32431322/47256460-9e445600-d49e-11e8-8110-6d24f8ced741.png)

I'm using Electron version: 3.0.5 and Devtron Version: 5.6.0

**Comment by ltfschoen** [comment]
I've got the same issue. Electron 2.02, Devtron 1.4.0.

<img width="1098" alt="screen shot 2019-01-14 at 10 11 07 am" src="https://user-images.githubusercontent.com/6226175/51091874-c82ebf80-17e4-11e9-9f72-67a87c9a8ee4.png">

I had setup Devtron before loading Dev Tools as follows

```
  // Enable with `DEBUG=true yarn start` and access in Dev Tools > Devtron
  debugSetup = () => {
    // Add Electron DevTools Extension (Devtron)
    if (withDebug && this.fetherApp.options.webPreferences.devTools) {
      require('devtron').install();
      this.fetherApp.window.webContents.openDevTools();
    }
  }
```

And the error occurs when I go to Developer Tools > Devtron > Require Graph,
And click the "Load Graph" button

**Comment by Treverix** [comment]
Same issue here - electron 4.0.4, devtron 1.4.0, MacOS 10.14.1

Load Graph does not work, throws this exception:

```
[62686:0223/173554.220149:ERROR:CONSOLE(1609)] "Loading render modules failed", source: chrome-extension://devtron/out/index.js (1609)
[62686:0223/173554.220223:ERROR:CONSOLE(1610)] "RangeError: Maximum call stack size exceeded
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:20:35)", source: chrome-extension://devtron/out/index.js (1610)
[62686:0223/173605.943449:ERROR:CONSOLE(1621)] "Loading main modules failed", source: chrome-extension://devtron/out/index.js (1621)
[62686:0223/173605.943490:ERROR:CONSOLE(1622)] "RangeError: Maximum call stack size exceeded
    at Object.array ([...]/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:12)
    at metaToValue ([...]/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:226:28)
    at Object.descriptor.get [as children] [...]/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:145:16)
    at walkModule (<anonymous>:21:26)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:21:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:21:35)
    at Array.map (<anonymous>)
    at walkModule (<anonymous>:21:35)", source: chrome-extension://devtron/out/index.js (1622)
```

**Comment by terror-jake** [comment]
From a Udemy course instructor, he stated that **Devtron team stopped development in favour of Chrome DevTools extension** so, no support is expected anymore.

**Comment by JasonXiaoSpace** [comment]
I do have the same problem, I use Electron(8.2.3)
