### ISSUE TITLE
Getting event listeners failed

### ISSUE THREAD

**Issue by davej** [electron/devtron#73]
I'm not sure if this is because I'm using `electron-prebuilt` or if something else is going on but I'm getting the following error in the main process when clicking 'Load Listeners':

```
[54624:0526/100818:ERROR:CONSOLE(413)] "Getting event listeners failed", source: chrome-extension://extension-1/out/index.js (413)
[54624:0526/100818:ERROR:CONSOLE(414)] "Error: value.hasOwnProperty is not a function
TypeError: value.hasOwnProperty is not a function
    at valueToMeta (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:70:22)
    at EventEmitter.<anonymous> (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at EventEmitter.<anonymous> (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at valueToMeta (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:70:22)
    at EventEmitter.<anonymous> (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at EventEmitter.<anonymous> (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at descriptor.get [as _events] (/Users/dave/code/forks/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:127:16)
    at getEvents (<anonymous>:23:26)
    at <anonymous>:37:45
    at <anonymous>:45:5
    at <anonymous>:49:9
    at Object.InjectedScript._evaluateOn (<anonymous>:145:167)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:137:25)
    at Object.InjectedScript.evaluate (<anonymous>:118:14)", source: chrome-extension://extension-1/out/index.js (414)
```

**Comment by kevinsawicki** [comment]
> I'm not sure if this is because I'm using electron-prebuilt

This shouldn't cause this issue, `electron-prebuilt` is totally fine to use with devtron

Would it be possible to share the app that you saw this error with? Was it just `electron-react-boilerplate` out of the box?

**Comment by davej** [comment]
@kevinsawicki You can see it by installing from this PR: https://github.com/chentsulin/electron-react-boilerplate/pull/227

**Comment by kevinsawicki** [comment]
> You can see it by installing from this PR

Awesome, thanks, will take a look today

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this.

This actually turns out to be a bug in Electron's IPC layer that is only now being hit because of node core changes in Electron 1.1+

I've submitted a pull request to fix this over in https://github.com/electron/electron/pull/5736

**Comment by davej** [comment]
Awesome, thanks for the investigation and resolution :)
